title: "Beyond Accuracy: Evaluating User Satisfaction in Movie Recommendations"
description: "Comparing accuracy, ranking quality, novelty, and diversity for different recommender models on the MovieLens datasets."
theme: jekyll-theme-cayman

# These two are important for a *project* site
url: "https://diyarahul.github.io"
baseurl: "/recsys-movielens-research"

# Let Jekyll know we have custom assets
plugins:
  - jekyll-seo-tag

# Make sure pages render with a default layout
defaults:
  - scope:
      path: ""
    values:
      layout: default
